services:
  - type: web
    name: shl-recommendation-app
    env: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
